apiVersion:  apps/v1  
kind: ReplicaSet
metadata: 
  name: rs-ml
  labels:
    app:  rs-ml
spec:   
    selector: 
      matchLabels: 
          app: newapp 
    replicas: 4 
    template:
          metadata: 
            name: newapp
            labels:
              app: newapp 
          spec: 
              containers: 
                - name: nginx
                  image: nginx:latest
                  ports:  
                  - containerPort: 80
                    protocol: TCP