apiVersion: v1  
kind: ReplicationController
metadata: 
  name: rc
  labels:
    app:  rc 
spec:   
    selector: 
          app: newapprc
    replicas: 4 
    template:
          metadata: 
            name: newapprc
            labels:
              app: newapprc
          spec: 
              containers: 
                - name: nginx
                  image: nginx:latest
                  ports:  
                  - containerPort: 80
                    protocol: TCP